### PR TITLE
Create aws_route_table without inline route. Route is then added to t…

### PR DESCRIPTION
**Pull request by mike-datascience**
Hi, thank you for your contribution to Mantl! Before we can accept any code into
master, we need it to meet the following criteria. If there are any you can't
satisfy yourself, go ahead and open the pull request anyway and we'll help you
test. Feel free to delete this message once you're done. Thanks again!

- [ ] Installs cleanly on a fresh build of most recent master branch
- [ ] Upgrades cleanly from the most recent release
- [ ] Updates documentation relevant to the changes

…he route_table.

### CODE REVIEW

**Comment by tphummel** [comment]
@mike-datascience looks good to me

**Comment by tphummel** [comment]
@mike-datascience prior to merge would you try a few `plan` and `apply` cycles to see how it works?

**Comment by mike-datascience** [comment]
Tried plan and apply. "No changes". Looks good.

**Comment by tphummel** [comment]
@mike-datascience good for merge

**Pull request merged**
